import { PriorityStats, RiskResult, Vulnerability } from "@/types/vulnerability";
import { calculateRisk } from "./risk-engine";

export const DEMO_VULNERABILITIES: Vulnerability[] = [
  {
    id: "vuln-01",
    cve: "CVE-2024-1709",
    description: "ConnectWise ScreenConnect authentication bypass vulnerability allowing remote administrative user creation and full server take-over.",
    cvss: 10.0,
    epss: 0.965,
    kev: true,
    exploitAvailable: true,
    internetExposed: true,
    assetName: "prod-vpn-gateway-01",
    assetCriticality: "critical",
    environment: "production",
    businessImpact: "critical",
    publishedDate: "2024-02-20",
    vendor: "ConnectWise",
    remediationAction: "Upgrade ConnectWise ScreenConnect to version 23.9.8 or higher immediately.",
  },
  {
    id: "vuln-02",
    cve: "CVE-2024-3094",
    description: "Malicious code in XZ Utils compression library enabling unauthorized SSH remote code execution.",
    cvss: 10.0,
    epss: 0.942,
    kev: true,
    exploitAvailable: true,
    internetExposed: true,
    assetName: "edge-ingress-proxy-02",
    assetCriticality: "critical",
    environment: "production",
    businessImpact: "critical",
    publishedDate: "2024-03-29",
    vendor: "XZ Utils",
    remediationAction: "Downgrade xz-utils to version 5.4.x or patch system packages via APT/YUM.",
  },
  {
    id: "vuln-03",
    cve: "CVE-2024-23897",
    description: "Jenkins CLI unauthenticated arbitrary file read vulnerability permitting SSH key extraction and RCE.",
    cvss: 7.5,
    epss: 0.915,
    kev: true,
    exploitAvailable: true,
    internetExposed: true,
    assetName: "jenkins-master-prod",
    assetCriticality: "critical",
    environment: "production",
    businessImpact: "critical",
    publishedDate: "2024-01-24",
    vendor: "Jenkins",
    remediationAction: "Upgrade Jenkins LTS to 2.440.2 or disable CLI access via system property.",
  },
  {
    id: "vuln-04",
    cve: "CVE-2024-21626",
    description: "runC container breakout flaw via file descriptor leak allowing host filesystem access.",
    cvss: 8.6,
    epss: 0.895,
    kev: true,
    exploitAvailable: true,
    internetExposed: true,
    assetName: "k8s-node-worker-04",
    assetCriticality: "critical",
    environment: "production",
    businessImpact: "critical",
    publishedDate: "2024-01-31",
    vendor: "Open Container Initiative",
    remediationAction: "Update runc to 1.1.12 or Kubernetes node OS kernel packages.",
  },
  {
    id: "vuln-05",
    cve: "CVE-2023-4863",
    description: "Heap buffer overflow in libwebp library leading to arbitrary code execution via forged WebP images.",
    cvss: 8.8,
    epss: 0.880,
    kev: true,
    exploitAvailable: true,
    internetExposed: true,
    assetName: "customer-portal-api",
    assetCriticality: "high",
    environment: "production",
    businessImpact: "high",
    publishedDate: "2023-09-12",
    vendor: "Google WebP",
    remediationAction: "Recompile application dependencies with libwebp 1.3.2+.",
  },
  {
    id: "vuln-06",
    cve: "CVE-2024-27198",
    description: "JetBrains TeamCity unauthenticated administrative account creation RCE vulnerability.",
    cvss: 9.8,
    epss: 0.875,
    kev: true,
    exploitAvailable: true,
    internetExposed: true,
    assetName: "build-server-01",
    assetCriticality: "high",
    environment: "production",
    businessImpact: "high",
    publishedDate: "2024-03-04",
    vendor: "JetBrains",
    remediationAction: "Update TeamCity to version 2023.11.4 or apply security patch plugin.",
  },
  {
    id: "vuln-07",
    cve: "CVE-2023-3519",
    description: "Unauthenticated Remote Code Execution in NetScaler ADC and Gateway.",
    cvss: 9.8,
    epss: 0.930,
    kev: true,
    exploitAvailable: true,
    internetExposed: true,
    assetName: "citrix-adc-ha-pair",
    assetCriticality: "critical",
    environment: "production",
    businessImpact: "critical",
    publishedDate: "2023-07-18",
    vendor: "Citrix Systems",
    remediationAction: "Apply NetScaler firmware build 13.1-49.13 or newer immediately.",
  },
  {
    id: "vuln-08",
    cve: "CVE-2023-22515",
    description: "Privilege escalation vulnerability in Confluence Data Center and Server allowing admin account creation.",
    cvss: 10.0,
    epss: 0.220,
    kev: false,
    exploitAvailable: false,
    internetExposed: false,
    assetName: "internal-wiki-docs",
    assetCriticality: "medium",
    environment: "staging",
    businessImpact: "medium",
    publishedDate: "2023-10-04",
    vendor: "Atlassian",
    remediationAction: "Apply Atlassian security upgrade to Confluence Server version 8.5.2.",
  },
  {
    id: "vuln-09",
    cve: "CVE-2024-20353",
    description: "Cisco ASA and Firepower Threat Defense Software denial of service vulnerability.",
    cvss: 8.6,
    epss: 0.650,
    kev: true,
    exploitAvailable: true,
    internetExposed: true,
    assetName: "edge-firewall-secondary",
    assetCriticality: "high",
    environment: "production",
    businessImpact: "high",
    publishedDate: "2024-04-24",
    vendor: "Cisco Systems",
    remediationAction: "Upgrade Cisco ASA software release to fixed maintenance build.",
  },
  {
    id: "vuln-10",
    cve: "CVE-2023-4966",
    description: "Citrix Bleed sensitive information disclosure flaw in NetScaler ADC and Gateway.",
    cvss: 9.4,
    epss: 0.840,
    kev: true,
    exploitAvailable: true,
    internetExposed: true,
    assetName: "dmz-loadbalancer",
    assetCriticality: "high",
    environment: "production",
    businessImpact: "high",
    publishedDate: "2023-10-10",
    vendor: "Citrix Systems",
    remediationAction: "Upgrade NetScaler firmware and kill active OAuth user sessions.",
  },
  {
    id: "vuln-11",
    cve: "CVE-2024-21887",
    description: "Ivanti Connect Secure and Policy Secure command injection vulnerability.",
    cvss: 9.1,
    epss: 0.890,
    kev: true,
    exploitAvailable: true,
    internetExposed: true,
    assetName: "ssl-vpn-concentrator",
    assetCriticality: "critical",
    environment: "production",
    businessImpact: "critical",
    publishedDate: "2024-01-12",
    vendor: "Ivanti",
    remediationAction: "Apply Ivanti rescue patch and run integrity check tool.",
  },
  {
    id: "vuln-12",
    cve: "CVE-2023-38545",
    description: "cURL SOCKS5 heap buffer overflow vulnerability.",
    cvss: 9.8,
    epss: 0.150,
    kev: false,
    exploitAvailable: false,
    internetExposed: false,
    assetName: "internal-analytics-batch",
    assetCriticality: "low",
    environment: "development",
    businessImpact: "low",
    publishedDate: "2023-10-11",
    vendor: "cURL Project",
    remediationAction: "Update libcurl package to version 8.4.0.",
  },
  {
    id: "vuln-13",
    cve: "CVE-2024-3400",
    description: "Palo Alto Networks PAN-OS command injection vulnerability in GlobalProtect feature.",
    cvss: 10.0,
    epss: 0.950,
    kev: true,
    exploitAvailable: true,
    internetExposed: true,
    assetName: "hq-edge-firewall-01",
    assetCriticality: "critical",
    environment: "production",
    businessImpact: "critical",
    publishedDate: "2024-04-12",
    vendor: "Palo Alto Networks",
    remediationAction: "Update PAN-OS to 10.2.9-h1, 11.0.4-h1, or 11.1.2-h3.",
  },
  {
    id: "vuln-14",
    cve: "CVE-2023-34048",
    description: "VMware vCenter Server out-of-bounds write vulnerability leading to RCE.",
    cvss: 9.8,
    epss: 0.450,
    kev: true,
    exploitAvailable: true,
    internetExposed: false,
    assetName: "internal-vcenter-cluster",
    assetCriticality: "high",
    environment: "production",
    businessImpact: "high",
    publishedDate: "2023-10-25",
    vendor: "VMware",
    remediationAction: "Apply vCenter Server patch release 7.0U3o / 8.0U2b.",
  },
  {
    id: "vuln-15",
    cve: "CVE-2024-21413",
    description: "Microsoft Outlook remote code execution vulnerability (Moniker Link flaw).",
    cvss: 9.8,
    epss: 0.620,
    kev: true,
    exploitAvailable: true,
    internetExposed: false,
    assetName: "windows-rdp-jumpbox",
    assetCriticality: "medium",
    environment: "production",
    businessImpact: "medium",
    publishedDate: "2024-02-13",
    vendor: "Microsoft",
    remediationAction: "Deploy Microsoft Patch Tuesday update KB5002537.",
  },
  {
    id: "vuln-16",
    cve: "CVE-2024-20359",
    description: "Cisco ASA and FTD Software persistent local privilege escalation vulnerability.",
    cvss: 6.0,
    epss: 0.080,
    kev: false,
    exploitAvailable: false,
    internetExposed: false,
    assetName: "lab-switch-cisco",
    assetCriticality: "low",
    environment: "development",
    businessImpact: "low",
    publishedDate: "2024-04-24",
    vendor: "Cisco Systems",
    remediationAction: "Restrict admin shell access and schedule routine firmware update.",
  },
  {
    id: "vuln-17",
    cve: "CVE-2023-29357",
    description: "Microsoft SharePoint Server elevation of privilege vulnerability allowing auth bypass.",
    cvss: 9.8,
    epss: 0.780,
    kev: true,
    exploitAvailable: true,
    internetExposed: true,
    assetName: "extranet-sharepoint-01",
    assetCriticality: "high",
    environment: "production",
    businessImpact: "high",
    publishedDate: "2023-06-13",
    vendor: "Microsoft",
    remediationAction: "Apply SharePoint Server Subscription Edition Security Update.",
  },
  {
    id: "vuln-18",
    cve: "CVE-2024-29972",
    description: "Zyxel NAS devices command injection vulnerability permitting unauthenticated remote execution.",
    cvss: 9.8,
    epss: 0.310,
    kev: true,
    exploitAvailable: true,
    internetExposed: false,
    assetName: "backup-nas-storage-02",
    assetCriticality: "medium",
    environment: "staging",
    businessImpact: "medium",
    publishedDate: "2024-06-03",
    vendor: "Zyxel",
    remediationAction: "Update NAS firmware to V5.21(AABT.5)C0 or isolate device network segment.",
  },
];

export function getVulnerabilities(): Vulnerability[] {
  return DEMO_VULNERABILITIES;
}

export function getEvaluatedResults(): RiskResult[] {
  const vulns = getVulnerabilities();
  const results = vulns.map((v) => calculateRisk(v));
  // Sort descending by calculated risk score
  return results.sort((a, b) => b.score - a.score);
}

export function getPriorityStats(results?: RiskResult[]): PriorityStats {
  const evaluated = results ?? getEvaluatedResults();
  const total = evaluated.length;
  const nowCount = evaluated.filter((r) => r.priority === "NOW").length;
  const nextCount = evaluated.filter((r) => r.priority === "NEXT").length;
  const laterCount = evaluated.filter((r) => r.priority === "LATER").length;
  const kevCount = evaluated.filter((r) => r.vulnerability.kev).length;
  const sumScore = evaluated.reduce((sum, r) => sum + r.score, 0);
  const avgRiskScore = total > 0 ? Math.round(sumScore / total) : 0;

  return {
    total,
    nowCount,
    nextCount,
    laterCount,
    kevCount,
    avgRiskScore,
  };
}
